# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.2.0
    # We might want to enable this at some point, but it requires some extra
    # setup (maybe generating the cache first?)
    #
    # See failure at:
    # https://buildkite.com/automattic/testpress-apple/builds/1#01818478-f45d-4dea-b629-e3bfb1ef6a57
    #
    # - automattic/git-s3-cache#v1.1.0:
    #     bucket: "a8c-repo-mirrors"
    #     repo: "Automattic/TestPress-Apple/"
  - &common_env
    IMAGE_ID: xcode-13.4.1
  - &common_agents
    queue: mac

steps:
  - label: UI Test (iPhone)
    # Notice we _need_ to use a script because of how our CI & VMs management
    # layer currently manages environment variables (which is how we make the
    # Test Analytics token available to the uploader)
    command: .buildkite/commands/build-and-ui-test.sh
    env: *common_env
    plugins: *common_plugins
    agents: *common_agents
