# frozen_string_literal: true

default_platform :ios

# It's necessary to be explicit with the DerivedData folder because that's
# where the xctestrun file will go.
PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))
DERIVED_DATA_PATH = File.join(PROJECT_ROOT_FOLDER, 'DerivedData')

platform :ios do
  lane :build_for_testing do |options|
    run_tests(
      project: 'TestPress.xcodeproj',
      scheme: options[:scheme],
      build_for_testing: true,
      derived_data_path: DERIVED_DATA_PATH
    )
  end

  lane :test_without_building do |options|
    # In the context of how this demo codebase works, it's enough for us to use
    # the first `.xctestrun` we find, because there's always going to be just
    # one.
    xctestrun_path = Dir.glob(File.join(DERIVED_DATA_PATH, 'Build', 'Products', '*.xctestrun')).first

    run_tests(
      project: 'TestPress.xcodeproj',
      scheme: options[:scheme],
      test_without_building: true,
      output_style: 'raw',
      xctestrun: xctestrun_path
    )
  end
end
